env:
  browser: true
  commonjs: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: "module"
plugins:
  - prettier
extends:
  - eslint:recommended
  - prettier
ignorePatterns:
  - node_modules
  - "**.min.js"
  - "**/dist/**"
rules:
  func-style:
    - error
    - expression
  arrow-body-style:
    - error
    - as-needed
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
  prefer-arrow-callback:
    - error
  no-unused-vars:
    - warn
  no-var:
    - error
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  prettier/prettier:
    - error
