env:
  browser: true
  commonjs: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: "module"
plugins:
  - prettier
extends:
  - eslint:recommended
  - prettier
ignorePatterns:
  - node_modules
  - "**.min.js"
  - "**/dist/**"
rules:
  prettier/prettier:
    - error
  func-style:
    - error
    - expression
  no-unused-vars:
    - warn
  no-var:
    - error
